name: Publish to NPM

on:
  push:
    branches:
      - master # Проверь, что ветка реально master, а не main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Мы НЕ пишем здесь registry-url, чтобы npm install прошел как обычно

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

