name: Publish to NPM

on:
  push:
    branches:
      - master # Или main, проверь как у тебя называется ветка

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npmjs.org' # Возвращаем сюда

      - name: Install dependencies
        run: npm install
        # Тут НЕ указываем env, чтобы npm install прошел без токена

      - name: Build CSS
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          # А вот тут токен ОБЯЗАТЕЛЕН
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
