name: Publish to NPM

on:
  push:
    branches:
      - master # Срабатывает при пуше в мастер

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # УБРАЛИ registry-url отсюда! Это решит проблему с npm install

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          # Указываем токен ТОЛЬКО здесь
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Если все равно будет 403, добавь принудительно реестр тут:
          npm_config_registry: "https://npmjs.org"

